---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: products-db
spec:
  provider: vault
  parameters:
    roleName: 'product'
    vaultAddress: 'http://vault:8200'
    objects: |
      - objectName: "db-username"
        secretPath: "hashicups/database/creds/product"
        secretKey: "username"
      - objectName: "db-password"
        secretPath: "hashicups/database/creds/product"
        secretKey: "password"