apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: source-controller
  namespace: flux-system
  annotations:
    kubernetes.io/service-account.name: "source-controller"
    kubernetes.io/service-account.namespace: "flux-system"