---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: database
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./database
  prune: true
  sourceRef:
    kind: GitRepository
    name: application-bootstrap
  targetNamespace: default