---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: repository
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./gitlab
  prune: true
  sourceRef:
    kind: GitRepository
    name: application-bootstrap
  targetNamespace: flux-system