---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./vault/kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: application-bootstrap
  targetNamespace: default